#!/bin/sh
# Front end for searching and writing notes
# Done with as simple userland tools as possible

notedir=$XDG_DATA_HOME/notes
# Scrub empty files
load() {
	cd $notedir || exit 1
	for i in *; do 
		if test -s $i; then 
			printf '%s\n' "$i"
		else 
			rm "$i"
		fi
	done
	printf "New\n"
}

## Main
test -d $notedir || mkdir -p "$notedir"
result=`load | dmenu -p "Create/edit note:"`

test -z $result && exit 0
case "$result" in
	New) exec /usr/local/share/notes/new ;;
	*)   edit "$notedir/$result" ;;
esac
